### ISSUE TITLE
Missing AllowSaveAsDraftAppointment

### ISSUE THREAD

**Issue by CPPOpa** [LinkeD365/OrgSettings#10]
Hello, I miss this option in the overview.
How can I add it?

Best regards
Peter

**Comment by LinkeD365** [comment]
Hey @CPPOpa, just run this tool up for the first time in a while and the setting is there

(I did sort Setting Name first)

![](https://user-images.githubusercontent.com/43988771/217051188-e67d172e-8e4f-4648-b37c-a2a75efbc947.png)

You are not seeing that?

**Comment by CPPOpa** [comment]
Hi, thanks for the quick reply.
I looked at the Settings.xml and found that this option is only available from 9.0.2.xxx.
My system is an 8.2.

**Comment by LinkeD365** [comment]
That was my next suggestion. I don't work with on prem often. The tool does
actively remove those that you cant use.
